### ISSUE TITLE
NullPointer exception on beginChat

### ISSUE THREAD

**Issue by omaroskars** [Mastersam07/livechat#2]
Followed the installation for Android. When i try to start the chat I get a nullpointer exception.

`<activity android:name="com.livechatinc.inappchat.ChatWindowActivity" android:configChanges="orientation|screenSize" />` Is in the manifest
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
E/MethodChannel#livechat( 7569): 	at android.content.ComponentName.<init>(ComponentName.java:131)
E/MethodChannel#livechat( 7569): 	at android.content.Intent.<init>(Intent.java:6510)
E/MethodChannel#livechat( 7569): 	at tech.mastersam.livechat.LivechatPlugin.onMethodCall(LivechatPlugin.java:82)
E/MethodChannel#livechat( 7569): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#livechat( 7569): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#livechat( 7569): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#livechat( 7569): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#livechat( 7569): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#livechat( 7569): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#livechat( 7569): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#livechat( 7569): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#livechat( 7569): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#livechat( 7569): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter ( 7569): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference, null) 
```

**Comment by Mastersam07** [comment]
Have you added:
`<activity android:name="com.livechatinc.inappchat.ChatWindowActivity" android:configChanges="orientation|screenSize" />`

in your android manifest?

**Comment by omaroskars** [comment]
@Mastersam07  Yes, The activity is in the manifest.

**Comment by omaroskars** [comment]
When I open the app in Intelli J, The manifest doesn't recognize ChatWindow activity for some reason. Do I need to install LiveChat in android Gradle?

**Comment by Mastersam07** [comment]
Can I have a minimum reproducible project?

**Comment by Mastersam07** [comment]
Where exactly in your manifest are you adding this?

`<activity android:name="com.livechatinc.inappchat.ChatWindowActivity" android:configChanges="orientation|screenSize" />`

**Comment by Mastersam07** [comment]
@omaroskars can you check the manifest in the example and confirm with what you have?

**Comment by omaroskars** [comment]
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="MY_PROJECT">

    <!-- The INTERNET permission is required for development. Specifically,
         flutter needs it to communicate with the running application
         to allow setting breakpoints, to provide hot reload, etc.
    -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    
    <!-- Access to biometrics-->
    <uses-permission android:name="android.permission.USE_FINGERPRINT"/>
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="@string/app_name"
        android:icon="@mipmap/launcher_icon">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            
            <!-- Notification for onResume and onLaunch-->
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter> 
        </activity>
        <activity android:name="com.livechatinc.inappchat.ChatWindowActivity" android:configChanges="orientation|screenSize" />
    </application>
</manifest>
```

**Comment by Mastersam07** [comment]
What plugin version are you using?

**Comment by Mastersam07** [comment]
Can I also get a reproducible project?

**Comment by Mastersam07** [comment]
I just tried replicating with livechat version `livechat: ^1.0.0+1` and I didn't encounter issues.

**Comment by omaroskars** [comment]
I think your plugin works as expected. The problem is probably with cached dependencies in my project, because I implemented the live chat plugin natively to begin with. I changed my native code to run "intent" like in this plugin does and everything works as expected.

Thanks a lot for your help
